# **Numpy 활용하기**

**배열 만들기 및 초기화**

In [ ]:
import numpy as np # 행렬 연산 기능을 제공하는 라이브러리

data = np.array([1,2,3,4,5,6]) # 1차원 배열 생성
data_2d = np.array([[1,2,3],[4,5,6]]) # 1차원 배열 생성
data_random = np.random.randn(2,3) # 2차원 배열 생성
data_zeros = np.zeros(5) # 0으로 초기화
data_ones = np.ones((2,3)) # 1로 초기화

print(data)
print(data_2d)
print(data_2d.shape)
print(data_random)
print(data_zeros)
print(data_ones)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 0.37019967 -1.1892322  -0.58748825]
 [-0.40490066  0.07928488 -0.89950065]]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


**배열 만들기(arange 활용)**

In [ ]:
import numpy as np

data_arange = np.arange(10, 121, 10) # 시작값 10 종료값 121 스텝 10
data_reshape = data_arange.reshape((2,6)) # data_arange 행렬의 shape을 2x6으로 변환

print(data_arange)
print(data_reshape)


[ 10  20  30  40  50  60  70  80  90 100 110 120]
[[ 10  20  30  40  50  60]
 [ 70  80  90 100 110 120]]


**배열의 요소 추출**

In [ ]:
import numpy as np

# 2차원 배열 선언
data = np.array([[1,2,3], 
                [4,5,6],
                [7,8,9]])
print(data)
print(data[0][1]) # data (0,1) 값 출력
print(data[0][1:]) # data 0번 째 배열의 두 번째 값부터 끝까지 출력

data[0] = 100 # data 0번 째 배열의 모든 요소에 100 대입
print(data) 
data[:] = 300 # data 배열의 모든 요소에 300 대입
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[2 3]
[[100 100 100]
 [  4   5   6]
 [  7   8   9]]
[[300 300 300]
 [300 300 300]
 [300 300 300]]


**배열의 산술 연산**

In [ ]:
import numpy as np

data= np.array([[5,7,9], [-7,-6,19], [6,8.9,11]])
data_2 = data * 2 # 모든 요소에 2를 곱함
data_3 = data + 3 # 모든 요소에 3을 더함

print(data)
print(data_2)
print(data_3)
print(data > data_2) # data와 data_2의 값들을 비교하여 data가 data_2보다 더 크면 True, 작으면 False를 반환

[[ 5.   7.   9. ]
 [-7.  -6.  19. ]
 [ 6.   8.9 11. ]]
[[ 10.   14.   18. ]
 [-14.  -12.   38. ]
 [ 12.   17.8  22. ]]
[[ 8.  10.  12. ]
 [-4.  -3.  22. ]
 [ 9.  11.9 14. ]]
[[False False False]
 [ True  True False]
 [False False False]]


**배열의 통계 메소드**

In [ ]:
import numpy as np

data= np.array([[5,7,9], [-7,-6,19], [6,8.9,11]])

print(data)
print(data.sum()) #배열 요소의 합계
print(data.mean()) #배열 요소의 평균
print(data.max()) #배열 요소 중 최댓값
print(data.min()) #배열 요소 중 최솟값
print(data.max(axis=0)) #열의 요소 값 중 최댓값을 구해서 얻은 배열 반환
index_1 = np.argmax(data, axis=0) #각 열에 대해 요소가 최댓값을 가지는 인덱스를 반환
print(index_1)

[[ 5.   7.   9. ]
 [-7.  -6.  19. ]
 [ 6.   8.9 11. ]]
52.9
5.877777777777777
19.0
-7.0
[ 6.   8.9 19. ]
[2 2 1]


**배열에 조건식 사용**

In [ ]:
import numpy as np

data= np.random.randn(3,2) # 가우시안 표준 정규분포 3x2 난수 배열 선언
print(data)
print(data > 0)
total = (data < 0).sum() #음수의 원소 개수
print(total)
data_minus = np.where(
    data < 0, 0, data) #data 중 음수만 골라서 0으로 변환
print(data_minus)

[[ 2.48863545e+00  2.04334416e+00]
 [-3.21874028e-01 -1.50487768e+00]
 [ 2.22242260e-01 -1.34152686e-03]]
[[ True  True]
 [False False]
 [ True False]]
3
[[2.48863545 2.04334416]
 [0.         0.        ]
 [0.22224226 0.        ]]


**배열의 요소 정렬**

In [ ]:
import numpy as np

data= np.array([[9,7,5], [19,-6,-9], [6,-2,11]])

print(data)
data.sort(0) #열의 요소 오름차순 정렬
print(data)
data.sort(1) #행의 요소 오름차순 정렬
print(data)

[[ 9  7  5]
 [19 -6 -9]
 [ 6 -2 11]]
[[ 6 -6 -9]
 [ 9 -2  5]
 [19  7 11]]
[[-9 -6  6]
 [-2  5  9]
 [ 7 11 19]]


**배열의 브로드캐스팅**

In [ ]:
import numpy as np

data_1 = np.array([[1,2,3], [4,5,6]])
data_2 = np.array([10,11,12])

sum = data_1 + data_2 #서로 다른 크기의 배열 연산 가능
multiply = data_1 * data_2
print(sum)
print(multiply)

[[11 13 15]
 [14 16 18]]
[[10 22 36]
 [40 55 72]]


# **2. Pandas 활용하기**

**Series 객체 생성 및 인덱스 설정**

In [ ]:
import pandas as pd

obj = pd.Series([10,20,30,40,50]) #pandas series를 사용하여 배열 선언
obj_2 = pd.Series([10,20,30,40,50], index=['a','b','c','d','e'])#index와 함께 배열 선언

print(obj)
print(obj.index) #객체의 인덱스
print(obj.values) #객체의 값 
print(obj[1]) #인덱스를 통해 값 접근
print('-' * 30)
print(obj_2)
print(obj_2[['a','e']]) #인덱스 'a','e'에 해당되는 요소 값 출력
print(obj_2[1:3]) #인덱스 1에서 2까지의 요소 값 출력

0    10
1    20
2    30
3    40
4    50
dtype: int64
RangeIndex(start=0, stop=5, step=1)
[10 20 30 40 50]
20
------------------------------
a    10
b    20
c    30
d    40
e    50
dtype: int64
a    10
e    50
dtype: int64
b    20
c    30
dtype: int64


**Series 객체의 연산과 조건식**

In [ ]:
import pandas as pd

obj = pd.Series([10,20,30,40])

print(obj * 10) # 모든 요소에 10을 곱하여 출력
print('-' * 30)
print(obj >= 20) # 20보다 크거나 같으면 True, 아니면 False 출력

0    100
1    200
2    300
3    400
dtype: int64
------------------------------
0    False
1     True
2     True
3     True
dtype: bool


**Series 객체와 for문**

In [ ]:
import pandas as pd

data = pd.Series([35, 60, 85], index=['유재석','박명수','태진아'])

print(data)
print('-' * 30)
for i, v in data.items() :  #item() 메소드 : Series 객체에 있는 요소를 튜플 형태로 반환
  print('%s : %d세'% (i,v))

유재석    35
박명수    60
태진아    85
dtype: int64
------------------------------
유재석 : 35세
박명수 : 60세
태진아 : 85세


**Series 객체와 딕셔너리**

In [ ]:
import pandas as pd

data = pd.Series({'유재석':35,'박명수':60,'태진아':85}, index=['유재석','박명수','태진아','정형돈','하하']) # 딕셔너리를 통해 value 값을 대입하면서 index 이름을 지정
data['정형돈']=52 # data 배열에서 index가 '정형돈'인 요소에 52 대입
print(data)
print(data[3])

유재석    35.0
박명수    60.0
태진아    85.0
정형돈    52.0
하하      NaN
dtype: float64
52.0


**DataFrame 객체 생성 및 인덱스 설정**

In [ ]:
import pandas as pd

data = {'이름':['유재석','박명수','정형돈','하하'],
        '나이':[35,60,52,38],
        '키':[180,175,160,150]}
frame = pd.DataFrame(data) # data를 DataFrame(Table 형식)으로 생성
frame_2 = pd.DataFrame(data, 
                       columns=['이름','나이','키','몸무게']) # column에 '몸무게'를 추가하여 DataFrame 생성
print(data)
print(frame)
print(frame_2)
print(frame.head(2)) #상위 n개 자료 출력
print(frame_2.tail(2)) #하위 n개 자료 출력

{'이름': ['유재석', '박명수', '정형돈', '하하'], '나이': [35, 60, 52, 38], '키': [180, 175, 160, 150]}
    이름  나이    키
0  유재석  35  180
1  박명수  60  175
2  정형돈  52  160
3   하하  38  150
    이름  나이    키  몸무게
0  유재석  35  180  NaN
1  박명수  60  175  NaN
2  정형돈  52  160  NaN
3   하하  38  150  NaN
    이름  나이    키
0  유재석  35  180
1  박명수  60  175
    이름  나이    키  몸무게
2  정형돈  52  160  NaN
3   하하  38  150  NaN


**DataFrame 요소 추출하기(loc과 iloc활용)**

In [ ]:
import pandas as pd 

data = {'이름':['유재석','박명수','정형돈','하하'],
        '나이':[35,60,52,38],
        '키':[180,175,160,150]}
frame = pd.DataFrame(data, index=['첫째','둘째','셋째','넷째'])
print(frame)
print(frame.loc['둘째','이름']) #행 인덱스가 '둘째'이고 열 인덱스가 '이름'에 해당되는 요소 반환
print(frame.loc['넷째',['나이','키']]) #행 인덱스가 '넷째'이고 열 인덱스 중 '나이', '키'에 해당되는 요소 반환
print('-' * 30) # '-' 30번 출력
print(frame.iloc[2,0]) #행 인덱스가 2이고 열 인덱스는 0인 요소 반환
print(frame.iloc[3,:2]) #행 인덱스가 3이고 열 인덱스는 0과 1인 열에 해당되는 요소 반환
print(frame.iloc[:,[0,2]]) #행 전체에 대해 열 인덱스가 0과 2인 요소 반환

     이름  나이    키
첫째  유재석  35  180
둘째  박명수  60  175
셋째  정형돈  52  160
넷째   하하  38  150
박명수
나이     38
키     150
Name: 넷째, dtype: object
------------------------------
정형돈
이름    하하
나이    38
Name: 넷째, dtype: object
     이름    키
첫째  유재석  180
둘째  박명수  175
셋째  정형돈  160
넷째   하하  150


**합계와 평균/정렬하기**

In [ ]:
import pandas as pd

data = {'이름':['유재석','박명수','정형돈','하하'],
        '나이':[35,60,52,38],
        '키':[180,175,160,150]}
frame = pd.DataFrame(data) # DataFrame 객체 생성
frame_2 = frame.iloc[:,[1,2]] #모든 행에 대해 열 인덱스 1,2인 열의 데이터 추출
rank = frame.sort_values(by=['나이'], ascending=False) # '나이'인덱스를 기준으로 내림차순으로 정렬하여 rank에 저장
total = frame_2.sum(axis=0) #frame_2에 저장된 나이, 키의 총 합계를 구함
avg = frame_2.mean(axis=0) #frame_2에 저장된 나이, 키의 평균을 구함

print(frame_2)
print(rank)
print(total)
print(avg)
#print(frame.describe()) #간단한 통계 확인하기

   나이    키
0  35  180
1  60  175
2  52  160
3  38  150
    이름  나이    키
1  박명수  60  175
2  정형돈  52  160
3   하하  38  150
0  유재석  35  180
나이    185
키     665
dtype: int64
나이     46.25
키     166.25
dtype: float64


**이번 강의도 수고 많으셨습니다. 감사합니다.**